### ISSUE TITLE
Invalid UUID string: eel

### ISSUE THREAD

**Issue by MarcinWieczorek** [Teapot418/eelbot#2]
I'm getting my client disconnected when trying to join the proxy.

Message:
Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.IllegalArgumentException: Invalid UUID string: eel

Console:
*** eelbot by TeapotDev (Minecraft 1.7.2-1.7.5) ***
Waiting for connection to proxy...
Status query!
Client connected to proxy! Connecting eel to target...
Connecting 1: d67c4f3896433327
Error connecting 1: unexpected packet
Error while sending keep alive: write tcp 127.0.0.1:58254: broken pipe

The server is 1.8, it's probably cos of that, but just leaving this issue so you can fix it or/and support 1.8

Thanks

**Comment by Teapot418** [comment]
I have written 1.8 support over a year ago, but never pushed this to Github until today. It's not tested, but should work. I no longer maintain this project, if something is not working you have to fix it on your own.
