### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by Cremaxx** [Teapot418/eelbot#3]
please help! i dont know what the shit that is xD
eelbot.go:6:8: cannot find package "bufio" in any of:
        /usr/local/go/src/bufio (from $GOROOT)
        ($GOPATH not set)
eelbot.go:7:8: cannot find package "bytes" in any of:
        /usr/local/go/src/bytes (from $GOROOT)
        ($GOPATH not set)
eelbot.go:9:8: cannot find package "crypto/rand" in any of:
        /usr/local/go/src/crypto/rand (from $GOROOT)
        ($GOPATH not set)
reader.go:5:8: cannot find package "encoding/binary" in any of:
        /usr/local/go/src/encoding/binary (from $GOROOT)
        ($GOPATH not set)
eelbot.go:8:8: cannot find package "encoding/hex" in any of:
        /usr/local/go/src/encoding/hex (from $GOROOT)
        ($GOPATH not set)
eelbot.go:3:8: cannot find package "flag" in any of:
        /usr/local/go/src/flag (from $GOROOT)
        ($GOPATH not set)
eelbot.go:5:8: cannot find package "fmt" in any of:
        /usr/local/go/src/fmt (from $GOROOT)
        ($GOPATH not set)
eelbot.go:12:8: cannot find package "io" in any of:
        /usr/local/go/src/io (from $GOROOT)
        ($GOPATH not set)
eelbot.go:4:8: cannot find package "net" in any of:
        /usr/local/go/src/net (from $GOROOT)
        ($GOPATH not set)
eelbot.go:11:8: cannot find package "os" in any of:
        /usr/local/go/src/os (from $GOROOT)
        ($GOPATH not set)
package .
        imports runtime: cannot find package "runtime" in any of:
        /usr/local/go/src/runtime (from $GOROOT)
        ($GOPATH not set)
eelbot.go:13:8: cannot find package "sync" in any of:
        /usr/local/go/src/sync (from $GOROOT)
        ($GOPATH not set)
eelbot.go:10:8: cannot find package "time" in any of:
        /usr/local/go/src/time (

**Comment by Teapot418** [comment]
It's problem with your Go installation, not with eelbot
