### ISSUE TITLE
Mam błąd

### ISSUE THREAD

**Issue by xThoorop** [Teapot418/eelbot#5]
Wyslałbyś skompilowanego eelbota?
Włączam .exe, i sie nic nie dzieje a zostaje to w procesach

**Comment by SlimxaQ** [comment]
Cześć,

Mi wszystko działa jednak pod włączeniu botów i połączeniu się do proxy mam problem: 

*** eelbot by TeapotDev (Minecraft 1.7.2-1.8.x) ***
## Waiting for connection to proxy...
# Status query!
## Client connected to proxy! Connecting eel to target...
# Connecting 1: add8b7db3f3166f0
# Error connecting 1: unexpected packet
# Connecting 1: 8bd6628970d6015c
# Error connecting 1: unexpected packet
# Connecting 1: 5e99dac158bfea37
# Error connecting 1: unexpected packet

:( Może razem uda nam się coś wymyślić? TS3: ts.xfast.pl Mail: slimxaq.server@gmail.com

Pozdro ;)

**Comment by xThoorop** [comment]
Jak będę miał chwilkę czasu to chętnie wbije.

**Comment by Teapot418** [comment]
@xThoorop Odpal z terminala/cmd.. :)

**Comment by SlimxaQ** [comment]
@Teapot418 A mi coś zaradzisz? :(

**Comment by Teapot418** [comment]
Której wersji MC używasz?

**Comment by SlimxaQ** [comment]
Serwer docelowy nie, testowałem z wszystkimi wersjami mc od 1.7 do 1.8.

Aktualnie miałem formata I nie mam jak tego sprawdzić fajnie by było jakbyś podał już skompilowany bo ja to chyba 1h kompiluje :D

**Comment by SlimxaQ** [comment]
Tzn. Testowałem to przed formatem ale z tego co pamiętam to od 1.7 do 1.8 i nic a teraz nie mogę tego potwierdzić czy tak robiłem bo miałem formata xD

**Comment by Teapot418** [comment]
Z tego co widzę to obsługa 1.8 (kompresji pakietów) jest wadliwa (od ponad roku nie zajmuję się już Minecraftem i wrzuciłem parę miesięcy jakąś nietestowaną starą wersję). Możliwe, że przy okazji zepsułem 1.7. Ponieważ już się tym nie zajmuję, cofnę wersje na Githubie do działającej wersji na 1.7
